server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: rhd
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848  #nacos服务地址
      discovery:
        cluster-name: HZ  #集群名称
        namespace: b064bfc3-03f3-454e-9fa3-2d8c44c4a127   #命名空间id
        ephemeral: false   #是否为临时实例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS






#只针对某个服务配置负载均衡策略
#userservice:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 负载均衡规则

userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则  集群优先，而后随机


#饥饿加载
ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients:
      - userservice  # 指定对哪个服务饥饿加载